# config.yaml

# --- General Settings ---
initial_potential: 'graph.pb'
seed_files:
  - 'seed/seed1.cif'
  - 'seed/seed2.cif'
output_file: 'selected_structures.xyz'

# --- Sampling Settings ---
sampling_mode: 'monte_carlo' # Options: 'monte_carlo', 'random_walk', 'molecular_dynamics'

# Monte Carlo (MC) Specifics
mc_params:
  ensemble: 'NVT'                # 'NVT' or 'NPT'
  pressures: [1.0,100.0]              # External pressure in bar (only for NPT)
  max_volume_change_fraction: 0.1 # Max fractional change in volume per NPT step
  temperatures: [300, 1000]
  max_displacement: 0.1
  num_steps: 50
  
# Random Walk (RW) Specifics
rw_params:
  perturbation_magnitude: 0.5 # Angstrom
  optimization_fmax: 1      # Force tolerance for local energy minimization (eV/A)
  num_walks: 300             # Number of random walks to perform

# Molecular Dynamics (MD) Specifics
md_params:
  ensemble: 'NVT'
  temperatures: [1000]
  pressures: [1.0] # List of pressures in bar
  n_steps: 5000
  timestep: 1.0
  save_interval: 1
  
# --- Filter Settings ---
filters:
  min_distance_check:
    enabled: true
    min_dist_matrix:
      'Au-Au': 2
      'Au-C': 1.2

  max_energy_check:
    enabled: true
    # Energy per atom above the relaxed seed energy. (eV)
    energy_tolerance: 1.8
  max_force_check:
    enabled: true
    # Max force component on any atom (eV/A)
    max_force_component: 15.0

# --- Selection Settings ---
selection_method: 'fps' # 'fps' or 'pca_grid'
selection_scope: 'global'         # Options: 'per_seed', 'global'
total_structures_to_select: 100

# Farthest Point Sampling (FPS) Specifics
fps_params:
  distance_metric: 'euclidean' # 'euclidean' or 'cosine'

# SOAP + PCA + Gridding Specifics
pca_grid_params:
  n_components: 2 # 2 or 3
  grid_size: [10, 10]

# --- SOAP Descriptor Settings ---
soap_params:
  species: ['Au', 'C', 'O']
  r_cut: 5.0  # Renamed from rcut
  n_max: 8    # Renamed from nmax
  l_max: 6    # Renamed from lmax
